version: '3'

services:
    redis:
      image: 'redis:latest'
      container_name: prod_redis_cash_flow
      command: redis-server --requirepass ${REDIS_PASSWORD} --maxclients ${REDIS_MAX_CLIENTS}
      env_file:
        - ./.env
      ports:
        - '5929:6379'
      volumes:
        - ./redis/data:/data
        - redis_data:/data

volumes:
    redis_data:
      driver: local
      driver_opts:
        type: none
        device: /home/redis/data
        o: bind
