apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-example
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "abc.paymeindia.in"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: django
            port:
              number: 8000

  - host: "cde.paymeindia.in"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 9000


