version: '3.7'

services:
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "80:80"
    volumes:
      - my-data:/var/lib/pgadmin
    env_file: .env

volumes:
    my-data: