version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
      #    image: yandex/clickhouse-client
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - ENABLE_OVERCOMMIT_MEMORY=true
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
