version: '2.2'
services:
  nginx:
    container_name: jenkins_nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - jenkins
    volumes:
      - /var/log/nginx/:/var/log/nginx/

  app:
    image: jenkins/jenkins
    container_name: jenkins_app
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - data:/var/jenkins_home
      - docker_certs:/certs/client:ro
      - ./ssh:/root/.ssh
    networks:
      - jenkins
    privileged: true
    user: root

  master_node:
    networks:
      - jenkins
    container_name: jenkins_master_node
    restart: always
    image: jenkins/ssh-agent
    privileged: true
    user: root
    expose:
      - 23
    volumes:
      - master_node:/home/jenkins
      - ./ssh:/var/jenkins_home/.ssh
      - ./ssh/config:/home/jenkins/.ssh/config
    depends_on:
      - app
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIXO6yaDZW9whX+qMh7z+dyal3UWHYqevQZsF+ViBUafisGS7Ui8zadP7QI8+72hyI6jd7KjdNTHynUVgzuesY1qEpgHqnoIDmMO4X5viyYFGg5dRb9Xecp+plPDDzShls+6El2gGObDXjkgLJdm0d9zBpJUnqpionijZJj93CHnump42j3Uoz55gmV24fa0awEws4fb2fZ2mH/LHQimjmfJqStlzxuo6ZBNq4YqhfrkCwR4WkUNOHys5w0ht2sPXwz5PzIMmPkdsJ/bemo8rKAsyci8g5j+Hngq6uQHxXTA0dAyehyM1bF1Wpr+SjORRuUZkcRPcNrMhc3T8h1L8q3pMhy9v10p14Q73mFGZXLB1z8L8TlNrvqb+C9kqNoriN5J9pVk/grKHbOtzl6HgEWg2GGALyc5rd5cFc5k6knMyWloydtFqW7gxkYxqtbIYOTeVkXndW1mMasGtVy3eokjl6VMRT/+tfpiEX5Dq32D/EHy52mY3K9FcxQLJXgj1gntN/xOz3Ea2ofoppyaTw1pTHzbXq4qYsEJiu9s6YMCkoZL3MQVaVXsApVbYJmVouDr7kOGeWuviM5TzrCEWwTdD0O1ynqo7Ya0bojbz5Eaax+j8p8ZQrbqTi1XNhrRaqUojDoc3eMU6QwnvQGaP84P7SsHd5NDxKnunR25Hu0Q== prod-jenkins.paymeindia.in

volumes:
  data:
    driver: local
  docker_certs:
    driver: local
  master_node:
    driver: local

networks:
  jenkins:
    driver: bridge