version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql57
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
