#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: postgres
#spec:
 # replicas: 1
  #selector:
   ##  name: postgres
 ##  metadata:
   #   labels:
    #    name: postgres
    #spec:
     # containers:
      #  - name: postgres
       #   image: postgres:latest
        #  ports:
         #   - containerPort: 5432
          #env:
           # - name: POSTGRES_USER
            #  value: "postgres"
            #- name: POSTGRES_PASSWORD
            # value: "postgres"
          # name: POSTGRES_DB
           #   value: "postgres"
         # volumeMounts:
         #   - mountPath: /var/lib/postgresql/data
          #    name: postgres-volume-mount
     # volumes:
      #  - name: postgres-volume-mount
       #   persistentVolumeClaim:
        #    claimName: postgres-pv-claim
---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    name: postgres
# END SERVICE
